/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const AppWindow: typeof import('./src/components/AppWindow')['default']
  const Launchpad: typeof import('./src/components/Launchpad')['default']
  const Notification: typeof import('./src/components/Notification')['default']
  const NotificationContainer: typeof import('./src/components/Notification')['NotificationContainer']
  const Spotlight: typeof import('./src/components/Spotlight')['default']
  const createRef: typeof import('react')['createRef']
  const forwardRef: typeof import('react')['forwardRef']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const motion: typeof import('framer-motion')['motion']
  const startTransition: typeof import('react')['startTransition']
  const useAudio: typeof import('react-use')['useAudio']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useInterval: typeof import('react-use')['useInterval']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useStore: typeof import('./src/stores/index')['useStore']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
  const useWindowSize: typeof import('react-use')['useWindowSize']
}
